### ISSUE TITLE
Add support for larger variety of commit log keyword formats

### ISSUE THREAD

**Issue by joakime** [jetty-project/jetty-version-maven-plugin#3]
@sbordet has started to use a a few new syntaxes for his commit messages that are not part of the detected patterns in the plugin.

    Fixes #123
    Fixed #456
    
See [eclipse/jetty.project@5c3e068cb3c2678b4602405a7bbd821f59d39b37] for example

**Comment by gregw** [comment]
Note also that when we merge PR's the commit messages are pretty much free form.

So we need to be really flexible.... scan the first like for any # numbers etc.   perhaps merge multiple commits with the same # number?  etc.

**Comment by joakime** [comment]
Fair enough, i'll implement that approach in a SNAPSHOT to see how it works out.

The `:whats-changed` goal from issue #5 would (hopefully) make this easier to troubleshoot too.

**Comment by sbordet** [comment]
@joakime you want to support at least these "keywords": https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by joakime** [comment]
The current implementation uses the recommended keywords, along with allowing a raw issue reference to appear at the start of the git commit subject line.  

Supporting arbitrary  "\#[0-9]{2,}" produced too much noise in the results.

**Comment by joakime** [comment]
Since the plugin can now pull the subject lines from github via the github api, the results are better anyway.
