### ISSUE TITLE
Add github api to pull the issue subject line

### ISSUE THREAD

**Issue by joakime** [jetty-project/jetty-version-maven-plugin#4]
Add support to use the github api to pull the commit message subject line.

**Comment by gregw** [comment]
We probably need to update our committing documentation/procedures to include updating subject lines to be more appropriate for inclusion in VERSION.txt    (I editing yours only really to be funny on this one :)

**Comment by joakime** [comment]
There is now support for pulling the issues list from github via its API.

The end results are *so much better* then relying on the commit subject line text
